version: 'build-{build}'
image: Visual Studio 2017
clone_folder: C:\projects\openfluid
skip_tags: true


environment:
  OFBUILD_MINGW_VERSION : 730_32
  OFBUILD_MINGW_VERSION_SHORT : 73_32
  OFBUILD_QT_VERSION : 5.13.2
  OFBUILD_SUPPORT_ARCHIVE : OpenFLUID-buildsupport-mingw730_32.7z
  OFBUILD_SUPPORT_DIR : C:\OpenFLUID-buildsupport-mingw730_32
  PRJ_DIR : C:\projects\openfluid
  BUILD_DIR : C:\projects\openfluid\_build-devel
  TOOLS_SUPPORT_ARCHIVE : OpenFLUID-support-testing-20201009.7z
  TOOLS_SUPPORT_DIR : C:\OpenFLUID-support


install:
  # download and installed already compiled support libraries
  - cmd: curl -fsS -o "%OFBUILD_SUPPORT_ARCHIVE%" "https://www.openfluid-project.org/resources/tools/%OFBUILD_SUPPORT_ARCHIVE%"
  - cmd: 7z x "%OFBUILD_SUPPORT_ARCHIVE%" -o"%OFBUILD_SUPPORT_DIR%\"
  - cmd: curl -fsS -o "%TOOLS_SUPPORT_ARCHIVE%" "https://www.openfluid-project.org/resources/tools/%TOOLS_SUPPORT_ARCHIVE%"
  - cmd: 7z x "%TOOLS_SUPPORT_ARCHIVE%" -o"%TOOLS_SUPPORT_DIR%\"


before_build:
  - cmd: cd %PRJ_DIR%
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  # Remove entry with sh.exe from PATH to fix error with MinGW Generator for CMake
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%  
  # Use MinGW from Qt tools instead of default installation
  - cmd: set PATH=%PATH:C:\MinGW\bin;=% 
  - cmd: set PATH=C:\Qt\Tools\mingw%OFBUILD_MINGW_VERSION%\bin;C:\Qt\%OFBUILD_QT_VERSION%\mingw%OFBUILD_MINGW_VERSION_SHORT%\bin;%PATH%
  - cmd: echo SET(OFBUILD_ENABLE_LANDR OFF) > %PRJ_DIR%\CMake.in.local.cmake
  - cmd: echo SET(OFBUILD_ENABLE_DOCS OFF) >> %PRJ_DIR%\CMake.in.local.cmake
  - cmd: type %PRJ_DIR%\CMake.in.local.cmake
  - cmd: cmake .. -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=%OFBUILD_SUPPORT_DIR%

  
build_script:
  - cmd: cd %BUILD_DIR%
  - cmd: mingw32-make -j 2


before_test:
  - cmd: set OPENFLUID_INSTALL_PREFIX=%BUILD_DIR%\dist
  - cmd: set PATH=%PATH%;%OFBUILD_SUPPORT_DIR%\bin;%OFBUILD_SUPPORT_DIR%\lib
  - cmd: set PATH=%PATH%;%BUILD_DIR%\dist\bin;%BUILD_DIR%\dist\lib
  - cmd: set PATH=%PATH%;%TOOLS_SUPPORT_DIR%\gnuplot-4.6.3\bin;%TOOLS_SUPPORT_DIR%\graphviz-2.36\bin;%TOOLS_SUPPORT_DIR%\ssl-1.1.1h


test_script:
  - cmd: ctest --output-on-failure