language: cpp

compiler:
  - gcc

env:
  global:
    - GCC_VERSION="4.8"
  matrix:
    - OFBUILD_TRAVIS_BUILDTYPE=debug
    - OFBUILD_TRAVIS_BUILDTYPE=release

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:czchen/travis-ci -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq openssh-server openssh-client "g++-${GCC_VERSION}" gfortran cmake libboost1.54-all-dev libqt4-dev libgdal1h libgdal1-dev libgeos++-dev p7zip-full gnuplot graphviz
  - sudo update-alternatives --install /usr/bin/g++ g++ "/usr/bin/g++-${GCC_VERSION}" 90

before_script:
  - echo "SET(BUILD_FORTRAN_SIMULATORS 1)" > CMake.in.local.cmake
  - echo "SET(BUILD_APP_DEVSTUDIO 1)" >> CMake.in.local.cmake
  - echo "SET(ENABLE_WARESDEV_BUILDER_INTEGRATION 1)" >> CMake.in.local.cmake
  - mkdir _build
  - cd _build
  - if [ ${OFBUILD_TRAVIS_BUILDTYPE} == "debug" ] ; then cmake .. -DOPENFLUID_ENABLE_HEAVYTESTING=1 ; fi
  - if [ ${OFBUILD_TRAVIS_BUILDTYPE} == "release" ] ; then cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ; fi

script:
  - if [ ${OFBUILD_TRAVIS_BUILDTYPE} == "debug" ] ; then make && ctest ; fi
  - if [ ${OFBUILD_TRAVIS_BUILDTYPE} == "release" ] ; then make && cpack -G DEB ; fi

notifications:
  email:
    on_success: always
    on_failure: always

